### ISSUE TITLE
"Discarding rows earlier"

### ISSUE THREAD

**Issue by lrweck** [pgMustard/pgMustard#23] opened 2019-11-19 20:35 UTC
With plan 8b9d97e5-8f30-4829-9899-68d0fea1f33c pgMustard suggests that I should discard rows earlier in both "Partial Aggregate" and "Finalize Aggregate", although PostgreSQL is doing a (pretty much) optimal plan with a parallel index only scan.

I am not sure what can I do to discard rows earlier.

**Comment by mchristofides** [comment] 2019-11-20 10:41
Thank you Luís, we'll have a think about how to improve this!

For a bit more context, we're not currently doing anything different for aggregate nodes. The issue is similar, in that the query is retrieving a lot of rows for relatively little output, although the advice on what to do is not quite right.

In your case, for an exact count, it does look almost optimal. An alternative we could consider linking to is considering a [count estimate](https://wiki.postgresql.org/wiki/Count_estimate). I'd be interested in how often this would be an option for you personally.

**Comment by lrweck** [comment] 2019-11-20 11:14
Thank you Michael!

Estimates are not really suited for my work, but I guess it can be for someone. So +1 on linking to it.

**Comment by hairybreeches** [comment] 2019-11-27 10:07
Hi Luis -

We've updated the logic for this tip so that it no longer occurs in aggregate-style scenarios like the one you encountered, and only shows up when rows are actively discarded, either as the result of a filter or a `LIMIT` operation.

Hopefully this will mean that it will only appear when it's relevant in future.

Thanks again for the feedback, keep it coming!

Dave

Fixed in commit 5e01bff064683567e82045ef811b7d1e8c68e032 deployed at 8:39 27/11/19

**Closed by hairybreeches** 2019-11-27 10:07 UTC
Labels: enhancement
